/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    candidates: Candidate;
    corrections: Correction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    candidates: CandidatesSelect<false> | CandidatesSelect<true>;
    corrections: CorrectionsSelect<false> | CorrectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidates".
 */
export interface Candidate {
  id: number;
  name: string;
  slug: string;
  party: string;
  /**
   * Asigna un numero para mostrar primero a los candidatos mas relevantes. Si se deja vacio, se ordena alfabeticamente.
   */
  directoryOrder?: number | null;
  currentOffice?: string | null;
  /**
   * Enlaces públicos oficiales del candidato. Se muestran en la ficha pública del perfil.
   */
  socialLinks?:
    | {
        platform: 'x' | 'instagram' | 'facebook' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Recursos adicionales que se muestran en la barra lateral del perfil del candidato.
   */
  additionalResources?: {
    /**
     * Enlace opcional a la sección de noticias del candidato en un medio de comunicación.
     */
    newsLink?: {
      enabled?: boolean | null;
      /**
       * Enlace directo a las noticias del candidato.
       */
      url?: string | null;
      /**
       * Logo del medio de comunicación (opcional).
       */
      outletLogo?: (number | null) | Media;
    };
  };
  photo: number | Media;
  lastUpdated: string;
  biography: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Cargos y roles en el sector público, gobierno, legislativo o vida política. Cada entrada aparece como un hito en la línea de tiempo de trayectoria pública.
   */
  publicTrajectoryItems?:
    | {
        role: string;
        organization: string;
        startYear: string;
        endYear?: string | null;
        location?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cargos y roles en el sector privado, académico o empresarial. Cada entrada aparece como un hito en la línea de tiempo de trayectoria privada.
   */
  privateTrajectoryItems?:
    | {
        role: string;
        organization: string;
        startYear: string;
        endYear?: string | null;
        location?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  proposals: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Cada entrada aparece como una tarjeta individual en el perfil del candidato. Las primeras 4 propuestas (en el orden de esta lista) se muestran en el perfil principal. Arrastra las filas para reordenar y elegir cuales 4 se destacan.
   */
  proposalItems?:
    | {
        title: string;
        description: string;
        topic?: string | null;
        sourceTitle: string;
        sourceUrl: string;
        sourceTier: 'oficial' | 'prensa' | 'ong' | 'redes';
        id?: string | null;
      }[]
    | null;
  controversies: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Cada entrada aparece como una tarjeta individual con codigo de color segun el estado. Las primeras 2 controversias se muestran en el perfil principal. Arrastra las filas para reordenar y elegir cuales se destacan.
   */
  controversyItems?:
    | {
        title: string;
        description: string;
        status: 'suspicion' | 'under_investigation' | 'indicted' | 'cleared' | 'convicted';
        year?: string | null;
        sourceTitle: string;
        sourceUrl: string;
        sourceTier: 'oficial' | 'prensa' | 'ong' | 'redes';
        id?: string | null;
      }[]
    | null;
  alliances: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Partidos y coaliciones que apoyan al candidato. Cada entrada muestra logo y nombre en una tarjeta.
   */
  allianceParties?:
    | {
        logo: number | Media;
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Personas relevantes que apoyan al candidato. Las primeras 4 se muestran en el perfil; si hay más, aparece el botón "Ver todos los apoyos".
   */
  endorsers?:
    | {
        photo: number | Media;
        name: string;
        id?: string | null;
      }[]
    | null;
  record: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  funding: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  sources?:
    | {
        section: 'biography' | 'proposals' | 'controversies' | 'alliances' | 'record' | 'funding';
        title: string;
        publishedAt: string;
        url: string;
        tier: 'oficial' | 'prensa' | 'ong' | 'redes';
        id?: string | null;
      }[]
    | null;
  /**
   * Videos de entrevistas al candidato en YouTube. Cada entrada se muestra en la pagina de entrevistas del perfil. Arrastra las filas para reordenar.
   */
  interviewItems?:
    | {
        title: string;
        /**
         * URL completa del video (ej: https://www.youtube.com/watch?v=XXXX o https://youtu.be/XXXX)
         */
        youtubeUrl: string;
        description?: string | null;
        publishedDate?: string | null;
        channel?: string | null;
        id?: string | null;
      }[]
    | null;
  summaryTrajectory: string;
  summaryProposals: string;
  summaryControversies: string;
  summaryAlliances: string;
  summaryRecord: string;
  summaryFunding: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections".
 */
export interface Correction {
  id: number;
  candidate: number | Candidate;
  note: string;
  correctedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'candidates';
        value: number | Candidate;
      } | null)
    | ({
        relationTo: 'corrections';
        value: number | Correction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidates_select".
 */
export interface CandidatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  party?: T;
  directoryOrder?: T;
  currentOffice?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  additionalResources?:
    | T
    | {
        newsLink?:
          | T
          | {
              enabled?: T;
              url?: T;
              outletLogo?: T;
            };
      };
  photo?: T;
  lastUpdated?: T;
  biography?: T;
  publicTrajectoryItems?:
    | T
    | {
        role?: T;
        organization?: T;
        startYear?: T;
        endYear?: T;
        location?: T;
        description?: T;
        id?: T;
      };
  privateTrajectoryItems?:
    | T
    | {
        role?: T;
        organization?: T;
        startYear?: T;
        endYear?: T;
        location?: T;
        description?: T;
        id?: T;
      };
  proposals?: T;
  proposalItems?:
    | T
    | {
        title?: T;
        description?: T;
        topic?: T;
        sourceTitle?: T;
        sourceUrl?: T;
        sourceTier?: T;
        id?: T;
      };
  controversies?: T;
  controversyItems?:
    | T
    | {
        title?: T;
        description?: T;
        status?: T;
        year?: T;
        sourceTitle?: T;
        sourceUrl?: T;
        sourceTier?: T;
        id?: T;
      };
  alliances?: T;
  allianceParties?:
    | T
    | {
        logo?: T;
        name?: T;
        id?: T;
      };
  endorsers?:
    | T
    | {
        photo?: T;
        name?: T;
        id?: T;
      };
  record?: T;
  funding?: T;
  sources?:
    | T
    | {
        section?: T;
        title?: T;
        publishedAt?: T;
        url?: T;
        tier?: T;
        id?: T;
      };
  interviewItems?:
    | T
    | {
        title?: T;
        youtubeUrl?: T;
        description?: T;
        publishedDate?: T;
        channel?: T;
        id?: T;
      };
  summaryTrajectory?: T;
  summaryProposals?: T;
  summaryControversies?: T;
  summaryAlliances?: T;
  summaryRecord?: T;
  summaryFunding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corrections_select".
 */
export interface CorrectionsSelect<T extends boolean = true> {
  candidate?: T;
  note?: T;
  correctedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}